import typing

FactionSelectionName = (
    str
    | typing.Literal[
        "applications",
        "attacks",
        "attacksfull",
        "balance",
        "basic",
        "chain",
        "chainreport",
        "chains",
        "contributors",
        "crime",
        "crimes",
        "crimeexp",
        "dirtbombs",
        "hof",
        "lookup",
        "members",
        "news",
        "positions",
        "rackets",
        "raidreport",
        "raids",
        "rankedwars",
        "rankedwarreport",
        "reports",
        "revives",
        "revivesfull",
        "search",
        "stats",
        "territory",
        "territoryownership",
        "territorywarreport",
        "territorywars",
        "timestamp",
        "upgrades",
        "warfarechains",
        "warfareraids",
        "warfareranked",
        "warfareterritory",
        "wars",
    ]
)
