import typing

PersonalStatsCategoryEnum = typing.Literal[
    "all",
    "popular",
    "attacking",
    "battle_stats",
    "jobs",
    "trading",
    "jail",
    "hospital",
    "finishing_hits",
    "communication",
    "crimes",
    "bounties",
    "investments",
    "items",
    "travel",
    "drugs",
    "missions",
    "racing",
    "networth",
    "other",
    "itemmarketcustomers",
    "itemmarketsales",
    "itemmarketrevenue",
    "itemmarketfees",
]
