import typing

TornItemTypeEnum = typing.Literal[
    "Alcohol",
    "Armor",
    "Artifact",
    "Book",
    "Booster",
    "Candy",
    "Car",
    "Clothing",
    "Collectible",
    "Drug",
    "Energy Drink",
    "Enhancer",
    "Flower",
    "Jewelry",
    "Material",
    "Medical",
    "Other",
    "Plushie",
    "Special",
    "Supply Pack",
    "Tool",
    "Unused",
    "Weapon",
]
