import typing

UserRankEnum = typing.Literal[
    "Absolute beginner",
    "Beginner",
    "Inexperienced",
    "Rookie",
    "Novice",
    "Below average",
    "Average",
    "Reasonable",
    "Above average",
    "Competent",
    "Highly competent",
    "Veteran",
    "Distinguished",
    "Highly distinguished",
    "Professional",
    "Star",
    "Master",
    "Outstanding",
    "Celebrity",
    "Supreme",
    "Idolized",
    "Champion",
    "Heroic",
    "Legendary",
    "Elite",
    "Invincible",
]
